### ISSUE TITLE
docker based tests no longer run on CI builds

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/acceptance-test-harness#1036]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>
  ci.jenkins.io
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

ci.jenkins.io

### Reproduction steps

1. run a build of the ATH on ci.jenkins.io

### Expected Results

tests that require docker are run

### Actual Results

tests that require docker are skipped

### Anything else?

https://github.com/jenkinsci/acceptance-test-harness/pull/878#issuecomment-1438571992

**Comment by raul-arabaolaza** [comment]
I can not assign this to myself, but I am working on this

**Comment by raul-arabaolaza** [comment]
I have confirmed by manually building https://github.com/jenkinsci/acceptance-test-harness/blob/200aafd9410b487aa184c5d92c639c3baacdc09d/src/main/resources/ath-container/Dockerfile that `docker` command executable is not present anymore in the image

**Comment by raul-arabaolaza** [comment]
Thanks @dduportal I suspect is just a matter of the `docker` split into the ce versions and I only need to update the ath dockerfile according to current docker installation instructions. Now the PR you linked contains a script to install docker that  I plan to ~copy~ errr, be inspired by :grin:

**Comment by dduportal** [comment]
@raul-arabaolaza ah ah yes feel free to copy/reuse/adapt as much as posible !

**Comment by raul-arabaolaza** [comment]
PR created to make docker based tests work again :crossed_fingers:

**Comment by dduportal** [comment]
@raul-arabaolaza @jtnord this issue seems closable, is that correct?
