### ISSUE TITLE
Majority of ATH tests are failing on CI

### ISSUE THREAD

**Issue by timja** [jenkinsci/acceptance-test-harness#1039]
### Reproduction steps

see https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/master/685/tests

### Expected Results

0 failing

### Actual Results

368 failing

### Anything else?

I ran `core.FreestyleJobTest#buildParametrized` locally against `2.392` in Firefox and it passed fine

**Comment by timja** [comment]
@NotMyFault attempted reverting the Ubuntu change, https://github.com/jenkinsci/acceptance-test-harness/pull/1040

But that wasn't the root cause.

Next steps I would suggest are running tests locally in ath-container to verify whether it can be reproduced there. Otherwise look towards infra more.

**Comment by timja** [comment]
From looking at recordings I saw two different issues.
1. Freestyle tests projects appear to be disabled after creating
2. Tests that go through plugin manager are timing out waiting for something.

I can reproduce in ath-container locally.

I can't reproduce on my local machine directly running in IntelliJ against 2.392 with firefox.

**Comment by timja** [comment]
Looks to be an issue with Firefox and selenium: https://github.com/jenkinsci/acceptance-test-harness/pull/1043

**Comment by timja** [comment]
I can reproduce locally after updating from Firefox 109 to Firefox 111

**Comment by raul-arabaolaza** [comment]
@timja I guess this can be closed now after #1043 ?
