### ISSUE TITLE
Dependabot uses wrong release notes

### ISSUE THREAD

**Issue by uhafner** [jenkinsci/acceptance-test-harness#1068]
The release notes are somehow broken. When Dependabot updates ATH in my project, then it shows the release notes of something unrelated. Is this a bug in dependabot or a bug here?

![Bildschirm­foto 2023-03-19 um 00 05 19](https://user-images.githubusercontent.com/503338/226144641-ef04168c-ba6e-41a4-a15c-bd29c847f564.png)

Example: https://github.com/jenkinsci/warnings-ng-plugin/pull/1470

**Comment by timja** [comment]
it will be missing info in the pom that is being inherited from the parent pom.

I think `<url>`
