### ISSUE TITLE
ATH doesn't work on recent Firefox

### ISSUE THREAD

**Issue by timja** [jenkinsci/acceptance-test-harness#1170]
### What feature do you want to see added?

- ATH to either have Firefox unpinned or automatically updated.
- ATH using the latest version of Firefox

### Upstream changes

see https://github.com/jenkinsci/acceptance-test-harness/pull/1043
and
https://github.com/jenkinsci/acceptance-test-harness/issues/1039

**Comment by raul-arabaolaza** [comment]
> It may be worth rethiking how we run the ATH so that we use selenium/firefox in a docker container separate from the SUT (and maven) aka remote-web-driver. This is how I always run locally and tend to not hit these types of issues.

Agree, That is also the way I run it since I decided I could not keep a native out of date web browser installation and keep a safe laptop at the same time...

**Comment by jtnord** [comment]
> ) [Guice/ErrorInCustomProvider]: SessionNotCreatedException: Could not start a new session. 

seems like https://github.com/SeleniumHQ/selenium/issues/12421 ?

**Comment by jtnord** [comment]
`error class java.util.LinkedHashMap cannot be cast to class org.openqa.selenium.Proxy`  oohkay....

**Comment by julieheard** [comment]
Can confirm that this works in 4.12.0 as that contains [this fix](https://github.com/SeleniumHQ/selenium/pull/12607).

**Comment by basil** [comment]
In #1637 I was able to successfully upgrade Firefox from 108.0.2 to 123.0.1, but upgrading to Firefox 124 or later is blocked on #1639.

**Comment by basil** [comment]
In #1657 I prepared this repository for Firefox 129 and newer, and in recent commits I enabled automatic updates of Firefox with Renovate, so when Firefox 129 is released on August 6, the Renovate PR should hopefully pass its CI build, at which point this ticket can be closed.
