### ISSUE TITLE
replace dependabot with renovate

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/acceptance-test-harness#1202]
### What feature do you want to see added?

Currently dependencies are managed partially by dependabot and partially by renovate with some overlap.

This is sub optimal as we can end up with duplicate PRs, or missed dependencies, and keeping config in sync/ optimal is cumbersome.

As renovate is more powerfull than dependabot we should switch to renovate.

https://github.com/jenkinsci/acceptance-test-harness/pull/1195#pullrequestreview-1451680336

**Comment by jtnord** [comment]
I am missing things that dependabot gives us like changelogs in the renovate PRs :(

e.g.   https://github.com/jenkinsci/acceptance-test-harness/pull/838 (db) vs https://github.com/jenkinsci/acceptance-test-harness/pull/1220 (renovate) renovate has no link to commits

**Comment by timja** [comment]
I think that is pretty niche, no release notes or changelog. but yes could be better.
