### ISSUE TITLE
`plugins.OwnershipPluginTest.explicitly_set_ownership` is failing

### ISSUE THREAD

**Issue by timja** [jenkinsci/acceptance-test-harness#1341]
e.g. https://github.com/jenkinsci/acceptance-test-harness/pull/1340

and a few others

**Comment by NotMyFault** [comment]
Is it beneficial to stick to testing the ownership plugin? It depends on Jenkins 1.x, has had no release since 2020, has 3 open security vulnerabilities and is unmaintained.

**Comment by timja** [comment]
> Is it beneficial to stick to testing the ownership plugin? It depends on Jenkins 1.x, has had no release since 2020, has 3 open security vulnerabilities and is unmaintained.

probably not, a few people have tried to move it to 2.x I think but it's quite difficult. If it has no maintainer and is stuck like that I think we should drop it
