### ISSUE TITLE
remove selenium:lift or fix renovate config

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/acceptance-test-harness#1407]
### Jenkins and plugins versions report

in https://github.com/jenkinsci/acceptance-test-harness/pull/1353 renovate proposed to update selenium but did not update to the latest release due to https://github.com/jenkinsci/acceptance-test-harness/pull/1353#discussion_r1377308490 

We should either fix the config so that lift is not tied to the selenium version (it has its own release cycle) or remove the dependency on lift that is only used in a single place.

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

N/A

### Expected Results

renoavte PRs to update selenium always pick aligned (and the latest) version.

### Actual Results

renovate picks an older version of the java libs than the docker libs.

**Comment by cathychan** [comment]
Looks like the reason is that `selenium:lift` has been deprecated and removed.
https://github.com/SeleniumHQ/selenium/blob/d65e38e34fc6ac29b7c2c62cc0b924d7f8762e6d/java/CHANGELOG#L177-L186

> v4.14.1
> ======
> * Add print, activate and set viewport commands to Browsing Context
> * Remove deprecated lift packages (#12917)
> * Add validation for browsing context id (#12920)
> * Fix default values for print options page size
> * Use the java process builder to run external processes (#12898)
> * Allow a custom timeout when shutting down a process
> * Replacing Guava implementations with native Java implementations
> * Allow setting version in Http Client Config (#12919)

So "remove selenium:lift" would be preferred.
