### ISSUE TITLE
All tests that touch script security approval are flakey

### ISSUE THREAD

**Issue by timja** [jenkinsci/acceptance-test-harness#1444]
looks like a regression in the script security plugin

revert https://github.com/jenkinsci/acceptance-test-harness/pull/1445 when fixed and any other recent suppressions

**Comment by timja** [comment]
cc @Vlatombe  / @jglick  likely cause is https://github.com/jenkinsci/script-security-plugin/pull/545

**Comment by jglick** [comment]
Can this be closed @timja?
