### ISSUE TITLE
adapt OicAuthPluginTest to https://github.com/jenkinsci/oic-auth-plugin/pull/399

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/acceptance-test-harness#1723]
### Jenkins and plugins versions report

https://github.com/jenkinsci/oic-auth-plugin/pull/399 changes the describables in the plugin. 
As such the test https://github.com/jenkinsci/acceptance-test-harness/blob/ef57fb36f31dc0178b205a6ddae2358de08bfe19/src/test/java/plugins/OicAuthPluginTest.java needs to be adapted

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

`export LOCAL_JARS=path/to/your/oic-auth-plugin/target/oic-auth.jpi`
`mvn test -Dtest=OicAuthPluginTest`

### Expected Results

Test passes

### Actual Results

test errors

### Anything else?

PR does not need to be compatible with the old version, so long as both PRs are merged at approximately the same time (the ATH PR should be merged when the plugin hits the UC).

**Comment by fcojfernandez** [comment]
PR to fix the test: https://github.com/jenkinsci/acceptance-test-harness/pull/1724

**Comment by fcojfernandez** [comment]
@jtnord PR is merged, I think this issue can be closed (I lack the permissions)
