### ISSUE TITLE
Default branch destabilized with 26 new test failures

### ISSUE THREAD

**Issue by basil** [jenkinsci/acceptance-test-harness#1803]
https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/1328/ has 26 new test failures. No new commits in this repository are responsible. I confirmed that Matrix Authorization Strategy is responsible and that downgrading from 3.2.3 to 3.2.2 resolves the errors.

**Comment by basil** [comment]
On further inspection, the failures start happening with jenkinsci/matrix-auth-plugin#159.

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/acceptance-test-harness/blob/master/src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/ProjectMatrixProperty.java#L24 needs to be adapted to the changed dialogs.
