### ISSUE TITLE
`core.PluginManagerTest#uninstall_plugin` is flakey

### ISSUE THREAD

**Issue by timja** [jenkinsci/acceptance-test-harness#741]
I've run this ~5 times locally and haven't managed to reproduce it but it's failing quite a bit on CI atm:

https://github.com/jenkinsci/acceptance-test-harness/runs/4958889552
https://github.com/jenkinsci/acceptance-test-harness/pull/730/checks?check_run_id=4965433217

cc @jtnord if you have any ideas

**Comment by jtnord** [comment]
[code](https://github.com/jenkinsci/acceptance-test-harness/blob/0f809be895ab9dfc2d3e9885d6da31578de03dbe/src/test/java/core/PluginManagerTest.java#L48-L59)

[failure](https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-730/11/testReport/core/PluginManagerTest/java_11_split3___uninstall_plugin/)

**Comment by jtnord** [comment]
offending element  https://github.com/jenkinsci/acceptance-test-harness/blob/0f809be895ab9dfc2d3e9885d6da31578de03dbe/src/test/java/core/PluginManagerTest.java#L55

https://www.javadoc.io/doc/org.seleniumhq.selenium/selenium-api/2.50.1/org/openqa/selenium/WebElement.html#submit--

according to the [javadoc ](https://www.javadoc.io/doc/org.seleniumhq.selenium/selenium-api/2.50.1/org/openqa/selenium/WebElement.html#submit--) form.submit() should block - did the recent plugin manager update or change unistallation at all?

**Comment by timja** [comment]
Didn't touch that page as far as I remember.

yeah I watched the .mov (required VLC, quicktime player couldn't use it) file and couldn't see anything weird

**Comment by jtnord** [comment]
https://github.com/jenkinsci/jenkins/pull/5916/files#diff-6c62cb488f832c1b63b4254b882e1d9319db662a61993e4dda76635f9fed7220R219-R223

the form changed from being a simple form with an input, to a form with a "jenkins" button (which may involve some asynchronous behaviour?

Anyway, a simple fix `would` seem to be adding a `waitFor(form).until(CapybaraPortingLayerImpl::isStale)` after the form submit and before the `clickButton()`
