### ISSUE TITLE
PluginManager.install(File) returns before the plugin has installed

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/acceptance-test-harness#804]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>
  Jenkins 2.346.1
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A but windows

### Reproduction steps

if a test calls [PluginManager.installPlugin(File)](https://github.com/jenkinsci/acceptance-test-harness/blob/be0a8371600593fba1f728dd1de1a2994b763d9a/src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java#L329-L358) the method returns *before* the plugin has been installed.

in a test have the following (not using the mock update center)
```
final File plugin = new File(getClass().getResource("foobar-1.0.hpi").toURI());
jenkins.getPluginManager().installPlugin(plugin);
jenkins.restart()
assertThat(/* the plugin is installed */)
```

### Expected Results

the assertion will always pass

### Actual Results

on my laptop it reliably fails.  the plugin has been uploaded but some of the background tasks to install it have not occured - which causes it to be "lost" after the restart.

### Anything else?

The method does not use selenium either so actually diagnosing what was going on was not so easy.  
Given https://github.com/jenkinsci/acceptance-test-harness/pull/780 we should use selenium and wait for the install to complete (regardless of if that completion requires a restart)

**Comment by NotMyFault** [comment]
Fixed in https://github.com/jenkinsci/acceptance-test-harness/pull/879
