### ISSUE TITLE
plugins.SshSlavesPluginTest.newAgent fails

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/acceptance-test-harness#866]
Named test fails with https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/524/testReport/junit/plugins/SshSlavesPluginTest/java_11_jenkins_latest_split4___newAgent/ on the default branch.

**Comment by jtnord** [comment]
Test passes with `2.346.2`  and `2.360` locally, I would guess the test is now flaky on latest @jmdesprez

**Comment by jtnord** [comment]
yes - test is flakey - [this is not how to interact with Jenkins dynamic UI elements](https://github.com/jenkinsci/acceptance-test-harness/blob/master/src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java#L35-L47).

clicks are asynchrously handled and can return at any time - it should click then wait for the subsequent menu.  
But even then it should not be doing this "by hand" but use a Credential pagearea.

**Comment by jtnord** [comment]
well the failure in [CI](https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-867/2/testReport/junit/plugins/SshSlavesPluginTest/java_11_jenkins_latest_split8___newAgent/) the HTML contains the following (formatted by me):

```
Expected condition failed: Element matching By.xpath: //div[contains(@class,'credentials-add-menu-items')]/div[@class='bd']/ul[@class='first-of-type']/li[contains(@class, 'yuimenuitem')]/span[contains(@class,'yuimenuitemlabel') and contains(@title, 'Jenkins Credentials Provider')] is present (tried for 120 second(s) with 500 milliseconds interval)
```


```
<div class="credentials-add-menu-items yuimenu yui-module yui-overlay yui-button-menu yui-menu-button-menu visible"
        id="yui-gen2"
        style="z-index: 1000; position: absolute; visibility: visible; left: 32px; top: 227px;">
        <div class="bd">
            <ul class="first-of-type">
                <li class="yuimenuitem first-of-type yuimenuitem-selected"
                    data-url="/descriptor/com.cloudbees.plugins.credentials.CredentialsSelectHelper/resolver/com.cloudbees.plugins.credentials.CredentialsSelectHelper$SystemContextResolver/provider/com.cloudbees.plugins.credentials.SystemCredentialsProvider$ProviderImpl/context/jenkins/dialog"
                    id="yui-gen8" groupindex="0" index="0">
                   <span
                        tooltip="Jenkins Credentials Provider"
                        class="yuimenuitemlabel yuimenuitemlabel-selected"
                        title="">
                        <!--?xml version="1.0" encoding="UTF-8"?-->
                        <svg class="symbol-jenkins icon-sm"
                            aria-hidden="true" width="413px" height="463px"
                            viewBox="0 0 413 463" version="1.1"
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink">
redacted
                        </svg>
                        Jenkins
                    </span></li>
            </ul>
        </div>
        <div class="yui-menu-shadow yui-menu-shadow-visible"></div>
    </div>
```

interestingly the `title` in the span is empty when run on ci.jenkins.io but not for me when run locally usigin the same Jenkins version (`2.360`)

I am not sure why this is behaving differently in the 2 environments.

**Comment by jtnord** [comment]
locally the title is present.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/494726/180794448-29de8fb9-54b2-4657-a5b7-e467a31304a6.png">
